### ISSUE TITLE
unable to select some nodes.

### ISSUE THREAD

**Issue by splace** [create3000/titania#45]
if you have a node, followed by a group with a clone of the first node.

````
#VRML V2.0 utf8 Titania V4.3.1

DEF Cone_1 Transform {
  children Shape {
    appearance Appearance {
      material Material { }
    }
    geometry Cone { }
  }
}

Transform {
  children USE Cone_1
}
````

then there doesn't seem anyway to select the second group, so you can not clone it etc.

**Comment by splace** [comment]
i now see i can, it's just that when selected the tree view shows it and its contents highlighted, AND the other first, cloned, transform, which is not effected by anything done to the selection. 

it also looks, in the tree view, the same as if you had selected both the first and second, the difference only being apparent from looking at them both in the browser panel, which might not be possible. 

is there a reason to highlight the clones of children nodes?

**Comment by create3000** [comment]
Yes, the selected node and all its children are highlighted and when a cloned node is a child its marked to be highlighted. This affects then all clones. The reason was that when you select a node with cloned children, some operations could affect all clones.

I have in a test project (not Titania) a solution where the behaviour is different, probably more what you think. But there the tree view is technically build in an other way. The main reason is this technical difference.

**Comment by create3000** [comment]
It will work as following:

```
#X3D V3.3 utf8 Titania V4.3.1

DEF Cone_1 Transform {
  children Shape {
    appearance Appearance {
      material Material { }
    }
    geometry Cone { }
  }
}

DEF Transform _2 {
  children USE Cone_1
}

```

* Selecting **DEF Transform _2** will highlight **Transform _2** and **USE Cone_1** but not **DEF Cone_1 Transform**
* Selecting **DEF Cone_1 Transform** will highlight **DEF Cone_1 Transform** and **USE Cone_1**

Or in other words only the node and descendant in the OutlineEditor's tree view are highlighted.

**Comment by splace** [comment]
> The reason was that when you select a node with cloned children, some operations could affect all clones.

i see. deeper issues.
