### ISSUE TITLE
javascript script float fields not comparable (works in x-ite)

### ISSUE THREAD

**Issue by splace** [create3000/titania#89]
```
#VRML V2.0 utf8 Titania V4.5.0

Script {
	field SFFloat f 0.001
	  url "javascript:
		  function initialize(){
			 Browser.println(f==0.001) 
	    }  
	  "
	}
}

// output: false
```

**Comment by create3000** [comment]
This is because you define f as SFFloat which is internally really a float with a precision of 6-7 digits but JavaScript uses alway double precision numbers. If you access f in JavaScript the float value is converted to double which result in a number like 0.0010000000474974513 which is not 0.01 double.

**Comment by create3000** [comment]
Use SFDouble values if you need to compare the values.

**Comment by splace** [comment]
> Use SFDouble values if you need to compare the values.

this is from a broken world i found, not from me (as are virtually all my reports) their whole usefulness is to show when the browser is not behaving as older browsers did.

**Comment by splace** [comment]
the standard requires this to work; because it specifies ISO/IEC 19775 ECMAScript, which is without typing, what seems to be happening is that you have used a more modern version of js (with typing) in a non backwardly-compatible manor.
